{% set version = "3.5.4" %}

package:
  name: maven
  version: {{ version }}

source:
  fn: apache-maven-{{ version }}-bin.tar.gz
  url: http://apache.hippo.nl/maven/maven-3/{{ version }}/source/apache-maven-{{ version }}-src.tar.gz
  sha256: f3ba1f1b24bbd4c345174ac616d40e26e72dad6022d56317d3ff6f7dd003e2f5

build:
  number: 0
  skip: true  # [win32]
  missing_dso_whitelist:
    # package includes libjansi DSO for various platforms, ignore them
    - '**libutil.so.1'
    - '**libutil.so.9'
    - '**libc.so.6'
    - '**libc.so.7'
    - '**libSystem.B.dylib'

requirements:
  build:
    - openjdk
  run:
    - openjdk

test:
  commands:
    - mvn -v

about:
  home: https://maven.apache.org
  license: Apachev2
  license_family: Apache
  license_file: LICENSE
  summary: A software project management and comprehension tool.
  description: |
    Apache Maven is a software project management and comprehension tool.
    Based on the concept of a project object model (POM), Maven can manage
    a project's build, reporting and documentation from a central piece of information.

extra:
  recipe-maintainers:
    - johanneskoester
    - hadim
