# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "yV44EGwiTKg6qLP/BrPpTLAte15SD0xBhVHYyAaN5LTt2gcbVIqjlgc1muXaFLyx+VDK+12WZO50w9MXva/whBJwHg/BBctMoTrQCvjy+q9SJO4Iqq3lpD/S30tM5cevB0OjZimTLwafYYQhz3o96A0iqpzG2I3ICqT1DBJKV+e3HYzpiQCZkVACm65+S1PE4oPE4kbenHbngCzWvcaKvwMm8O3s5On3yQlOff7wGaqdQRosomrSts8EUnkojb3PAgXCvpfSz3QSKKx6lA/WYuljDcjyFNmJyFrKJy9hEBjDHi516zY+nb39bQnM22THRUbgAp4CiIeW2w9wi7YrUGESnRt5AS3i9TOXYWAyb79LExib7KcWyQZQoNeF1GkOSMvuYs8ER+emnmzAxBL1S6lE4YO96kegAkrYBJ/bK++pQc3P7sygXsvRx5y9tGv7ld5i8OSoRw6hDZTMGSoIU+cswJmWxTq95+pPr2CepVtuz1bTaHDaodrXArLAdUD2Cy0KfRnsChoVEaWg61Mso/a9TFF3ZaXjqH9f/KaDU3eOEHKIhM1mQpvsPIzRdwHS4HhccnNcdPLvaFxhhMVivgzrKQa01A8DecMaREa+L66sioebhlR9s6uAUeii6L/Mh9+usbo3FmhLo/OFuyOKjU+o7CZJa36pW4eotCu/u2c="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
